package com.arbolesyazilim.manifestolumlama

object Constants {

    fun getManifests(): ArrayList<Manifest>{
        val manifestList = ArrayList<Manifest>()
        val manifest1 = Manifest(1, "Ben hayatımı tüm güzellikleri ve iyilikleri ile yükseltiyorum. ")
        manifestList.add(manifest1)
        val manifest2 = Manifest(2, "Mucizeleri fark ediyorum.")
        manifestList.add(manifest2)
        val manifest3 = Manifest(3, "Yaşamın güzelliklerini görüyorum.")
        manifestList.add(manifest3)
        val manifest4 = Manifest(4, "Her ne oluyorsa benim hayrıma oluyor.")
        manifestList.add(manifest4)
        val manifest5 = Manifest(5, "Hayatı akışına bırakıyorum.")
        manifestList.add(manifest5)
        val manifest6 = Manifest(6, "Kendimi beğeniyorum.")
        manifestList.add(manifest6)
        val manifest7 = Manifest(7, "Etrafımı beni seven, destek olan insanlar sarıyor.")
        manifestList.add(manifest7)
        val manifest8 = Manifest(8, "Huzurla güne başlıyorum.")
        manifestList.add(manifest8)
        val manifest9 = Manifest(9, "Mutluluğu seçiyorum.")
        manifestList.add(manifest9)
        val manifest10 = Manifest(10, "Başarıya odaklanıyorum.")
        manifestList.add(manifest10)
        val manifest11 = Manifest(11, "Kendimi güvende hissediyorum.")
        manifestList.add(manifest11)
        val manifest12 = Manifest(12, "Para bana kolaylıkla gelir.")
        manifestList.add(manifest12)
        val manifest13 = Manifest(13, "Bolluk içinde olmayı seçiyorum.")
        manifestList.add(manifest13)
        val manifest14 = Manifest(14, "Saygı duyulmasını seçiyorum.")
        manifestList.add(manifest14)
        val manifest15 = Manifest(15, "Neşe frekansında kalmayı seçiyorum.")
        manifestList.add(manifest15)
        val manifest16 = Manifest(16, "Hayatım bereket dolu.")
        manifestList.add(manifest16)
        val manifest17 = Manifest(17, "Ben hayatımda tüm güzellikleri ve iyilikleri kolaylıkla kendime çekiyorum.")
        manifestList.add(manifest17)
        val manifest18 = Manifest(18, "Hayatım sürekli en güzel şekilde değişiyor ve gelişiyor.")
        manifestList.add(manifest18)
        val manifest19 = Manifest(19, "Bolluk, bereket yaratanın izniyle bana kolaylıkla geliyor.")
        manifestList.add(manifest19)
        val manifest20 = Manifest(20, "Hiç dünyamdaki huzur mutluluk ve enerji her geçen gün daha da büyüyor.")
        manifestList.add(manifest20)
        val manifest21 = Manifest(21, "Her zaman etrafımdan saygı gören, sözü dinlenen ve güvenilen biriyim.")
        manifestList.add(manifest21)
        val manifest22 = Manifest(22, "Hayatın güzellikleri her an beni kolaylıkla buluyor.")
        manifestList.add(manifest22)
        val manifest23 = Manifest(23, "Yaptığım her işte iç huzurun keyfini yaşıyor daha güzel günlere adım atıyorum.")
        manifestList.add(manifest23)
        val manifest24 = Manifest(24, "Kendime çok seviyor, sıkıca kucaklıyor ve kabul ediyorum.")
        manifestList.add(manifest24)
        val manifest25 = Manifest(25, "Ebedi mutluluk, sağlık, başarı ve bolluk bereket hep benimle.")
        manifestList.add(manifest25)
        val manifest26 = Manifest(26, "Etrafımda beni seven, önem veren mükemmel insanlar var.")
        manifestList.add(manifest26)
        val manifest27 = Manifest(27, "Hayatıma her an beni daha da ileriye taşıyacak kişileri çekiyorum.")
        manifestList.add(manifest27)
        val manifest28 = Manifest(28, "Geçmişimi seviyor, onu orada bırakarak huzur sevgi ile affediyorum.")
        manifestList.add(manifest28)
        val manifest29 = Manifest(29, "Geleceğe dair tüm güzellikleri her gün kendime hediye ediyorum.")
        manifestList.add(manifest29)
        val manifest30 = Manifest(30, "Her an huzurla ve ihlasla dua ediyor ve dualarıma karşılık alıyorum.")
        manifestList.add(manifest30)
        val manifest31 = Manifest(31, "Ebedi sağlık, gençlik, güzellik, mutluluk, huzur ve sevgi beni kolaylıkla buluyor.")
        manifestList.add(manifest31)
        val manifest32 = Manifest(32, "Geçmişim beni hızla yukarıya taşıyan başarı merdivenlerini dönüşüyor.")
        manifestList.add(manifest32)
        val manifest33 = Manifest(33, "Bolluk, bereket bol kazanç bana kolaylıkla geliyor.")
        manifestList.add(manifest33)
        val manifest34 = Manifest(34, "İstediğim işi kolaylıkla yapıyor ve bol para kazanıyorum.")
        manifestList.add(manifest34)
        val manifest35 = Manifest(35, " Dev bir mıknatıs gibi başarıyı, bol kazancı kendime çekiyorum")
        manifestList.add(manifest35)
        val manifest36 = Manifest(36, "Bolluk, bereket, aşk ve iş alanında en doğru kararları alıyorum.")
        manifestList.add(manifest36)
        val manifest37 = Manifest(37, "Tükettiğim yiyecekler bana sağlık, gençlik, dinçlik ve güzellik oluyor.")
        manifestList.add(manifest37)
        val manifest38 = Manifest(38, "Bilgeliğim her geçen gün artarken yüreğimdeki sevgi daha da büyütüyor.")
        manifestList.add(manifest38)
        val manifest39 = Manifest(39, "Hayatımdaki her şey  kolaylıkla ve hızlıca olması gerektiği gibi oluyor.")
        manifestList.add(manifest39)
        val manifest40 = Manifest(40, " Olumlu düşüncelerim doğrultusunda hayatım olumlu bir şekilde geçiyor.")
        manifestList.add(manifest40)
        val manifest41 = Manifest(41, "Maddi bolluğum ne kazancım her geçen gün daha da artıyor.")
        manifestList.add(manifest41)
        val manifest42 = Manifest(42, "Yüksek enerjim ile enerjimi daha da yükseltecek şeyleri kendime çekiyorum.")
        manifestList.add(manifest42)
        val manifest43 = Manifest(43, "Her zaman affederek kendimi  kuşlar gibi özgür bırakıyorum.")
        manifestList.add(manifest43)
        val manifest44 = Manifest(44, "Hayatımın her alanında sevdiklerim ile birlikte güven içindeyim, korunuyorum.")
        manifestList.add(manifest44)
        val manifest45 = Manifest(45, "Bilgelik, başarı, bolluk bereket potansiyelim sonsuz.")
        manifestList.add(manifest45)
        val manifest46 = Manifest(46, "Yüce yaratıcının sunduğu zenginliği, bolluğu, ihtişamı, bereketi ve sağlığı alıyorum.")
        manifestList.add(manifest46)
        val manifest47 = Manifest(47, "Hayatımın her alanında, her an bolluk  içindeyim.")
        manifestList.add(manifest47)
        val manifest48 = Manifest(48, "Ruhumu besleyen pozitif, sevgi dolu ve enerjik insanlarla birlikte olmayı seçiyorum.")
        manifestList.add(manifest48)
        val manifest49 = Manifest(49, "Ben kazanan bir insanım")
        manifestList.add(manifest49)
        val manifest50 = Manifest(50, "Mucizelere açılmayı seçiyorum.")
        manifestList.add(manifest50)
        val manifest51 = Manifest(51, "Frekansımı yükseltecek durumları kendime çekiyorum.")
        manifestList.add(manifest51)
        val manifest52 = Manifest(52, "BENİM DÜNYAMDA HER ŞEY YOLUNDADIR, BENİM DÜNYAMDA BOLLUK VE BEREKET SINIRSIZDIR. ")
        manifestList.add(manifest52)
        val manifest53 = Manifest(53, "HAYATIMI GÜZELLEŞTİRECEK OLUŞLARI VE İNSANLARI KENDİME ÇEKİYORUM. ")
        manifestList.add(manifest53)
        val manifest54 = Manifest(54, "YAŞAMIN AKIŞINA VE KADERİMİN YOLUNA GÜVENİYORUM, HUZURLUYUM. ")
        manifestList.add(manifest54)
        val manifest55 = Manifest(55, "Bedenime özen gösteriyorum.")
        manifestList.add(manifest55)
        val manifest56 = Manifest(56, "BEN DAİMA BULUNDUĞUM ANIN GÜZELLİĞİNİ YAŞIYORUM.")
        manifestList.add(manifest56)
        val manifest57 = Manifest(57, "YAŞAMA DAİR YENİ DENEYİMLERİ MUTLULUKLA KABUL EDİYORUM. ")
        manifestList.add(manifest57)
        val manifest58 = Manifest(58, "HER ZAMAN GÜVEN İÇİNDEYİM, SEVGİ BENİ KUŞATIYOR VE KORUYOR. ")
        manifestList.add(manifest58)
        val manifest59 = Manifest(59, "AKLIM VE SEZGİLERİM BANA EN DOĞRU YOLU GÖSTERİYOR. ")
        manifestList.add(manifest59)
        val manifest60 = Manifest(60, "YAŞAM SÜREKLİ DEĞİŞİKLİKLER İÇİNDE VE BEN BU DEĞİŞİKLİKLERE KOLAYCA UYUM SAĞLIYORUM. ")
        manifestList.add(manifest60)
        val manifest61 = Manifest(61, "YAŞAMIM TÜM YÖNLERİYLE RAHATLIYOR, BİLİNCİM TÜM ENGELLERDEN ARINIYOR. ")
        manifestList.add(manifest61)
        val manifest62 = Manifest(62, "BAKMAKTAN VE YAŞAMAKTAN SONSUZ ZEVK ALACAĞIM BİR YAŞAM YARATIYORUM.")
        manifestList.add(manifest62)
        val manifest63 = Manifest(63, "HER DÜŞÜNCEM VE DAVRANIŞIM HAYATIMI DAHA İYİ BİR HALE GETİRİR. ")
        manifestList.add(manifest63)
        val manifest64 = Manifest(64, "İÇİMDE HİSSETTİĞİM CESARET VE GÜÇ BANA TÜM KAPILARI AÇIYOR.")
        manifestList.add(manifest64)
        return manifestList
    }
}